import bizTenderActionTypes from 'applications/biz-tender/redux/actions/types';

const TYPES = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SET: 'AUTH_SET',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_UNSET: 'AUTH_UNSET',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',

  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_REQUEST: 'FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_REQUEST',
  FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_SUCCESS: 'FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_SUCCESS',
  FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_ERROR: 'FETCH_USER_DETAILS_WITH_PASSWORD_TOKEN_ERROR',

  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',

  // Apps
  ALL_APP_REQUEST: 'ALL_APP_REQUEST',
  ALL_APP_SUCCESS: 'ALL_APP_SUCCESS',
  ALL_APP_ERROR: 'ALL_APP_ERROR',

  ALL_APP_BY_CATEGORY_REQUEST: 'ALL_APP_BY_CATEGORY_REQUEST',
  ALL_APP_BY_CATEGORY_SUCCESS: 'ALL_APP_BY_CATEGORY_SUCCESS',
  ALL_APP_BY_CATEGORY_ERROR: 'ALL_APP_BY_CATEGORY_ERROR',

  INSTALL_APP: 'INSTALL_ALL',
  UNINSTALL_APP: 'UNINSTALL_ALL',

  SEARCH_TEXT: 'SEARCH_TEXT',
  ...bizTenderActionTypes
};
export default TYPES;
