const TYPES = {
  TENDER_REQUEST: 'TENDER_REQUEST',
  TENDER_SUCCESS: 'TENDER_SUCCESS',
  TENDER_FAILURE: 'TENDER_FAILURE',
  DETAILS_REQUEST: 'DETAILS_REQUEST',
  DETAILS_SUCCESS: 'DETAILS_SUCCESS',
  DETAILS_FAILURE: 'DETAILS_FAILURE',

  // Sort By
  TENDER_CHANGE_FILTER: 'TENDER_CHANGE_FILTER',
  TENDER_SORT_BY: 'TENDER_SORT_BY',
  TENDER_UPDATE_SEARCH_TEXT: 'TENDER_UPDATE_SEARCH_TEXT'
};

export default TYPES;
